function [ang_q,n] = AngleAxe_from_Rot (R)
    % Angle de rotation équivalent à une rotation donnée
    ang_q = atan2(0.5*sqrt((R(3,2) - R(2,3))^2 +...
                (R(1,3) - R(3,1))^2 + (R(2,1) - R(1,2))^2), ...
                0.5*(R(1,1)+ R(2,2) + R(3,3)-1));
    % Axe de rotation équivalent à une rotation donnée
    n = [(R(3,2) - R(2,3))/(2*sin(ang_q)), ...
        (R(1,3) - R(3,1))/(2*sin(ang_q)), ...
        (R(2,1) - R(1,2))/(2*sin(ang_q))];
end